name: analytica
description: Simple auth app flutter, server node.js, BLoC pattern, RxDart.

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^0.1.3
  flutter_sparkline: "^0.1.0"
  flutter_staggered_grid_view: "^0.2.5"
  flutter_circular_chart: ^0.1.0
  font_awesome_flutter: ^8.2.0


  path: ^1.6.4
  http: ^0.13.6
  built_value: ^7.1.0
  tuple: ^1.0.3
  rxdart: ^0.24.0
  image_picker: ^0.6.5+2
  shared_preferences: ^0.5.7

  # my packages
  distinct_value_connectable_stream: ^1.1.1
  flutter_provider: ^1.1.1
  rx_shared_preferences: ^1.2.0
  disposebag: ^1.1.2
  flutter_bloc_pattern: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.9.0
  built_value_generator: ^7.1.0
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  image_path: "assets/logo500.png"
  ios: true
  android: true

flutter:
  uses-material-design: true
  assets:
   - assets/background.jpg
   - assets/logo.png
   - assets/bg_home.jpg
   - assets/logo500.png
